name: e_commerce_app
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_carousel_widget: ^2.2.0
  firebase_auth: ^4.17.4
  cloud_firestore: ^4.15.5
  fluttertoast: ^8.2.4
  google_sign_in: ^6.2.1
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/logo.png
    - assets/images/m1.jpeg
    - assets/images/m2.jpg
    - assets/images/shirt.jpeg
    - assets/images/shirt2.jpg
    - assets/images/shirt0.jpeg
    - assets/images/shirt1.jpg
    - assets/images/dress.jpeg
    - assets/images/dress2.jpg
    - assets/images/dress3.jpeg
    - assets/images/dress4.jpeg
    - assets/images/pant1.jpg
    - assets/images/pant2.jpeg
    - assets/images/pant3.jpg
    - assets/images/shoe1.jpeg
    - assets/images/shoe2.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic

